/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SuggestedRouteImport } from './routes/suggested'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OrganiserRouteImport } from './routes/organiser'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MunicipalityRouteImport } from './routes/municipality'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterestsRouteImport } from './routes/interests'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminMatchRouteImport } from './routes/admin-match'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventIdRouteImport } from './routes/event.$id'
import { Route as ApiPlacesDetailsRouteImport } from './routes/api/places.details'
import { Route as ApiPlacesAutocompleteRouteImport } from './routes/api/places.autocomplete'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SuggestedRoute = SuggestedRouteImport.update({
  id: '/suggested',
  path: '/suggested',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganiserRoute = OrganiserRouteImport.update({
  id: '/organiser',
  path: '/organiser',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalityRoute = MunicipalityRouteImport.update({
  id: '/municipality',
  path: '/municipality',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRoute = InterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMatchRoute = AdminMatchRouteImport.update({
  id: '/admin-match',
  path: '/admin-match',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesDetailsRoute = ApiPlacesDetailsRouteImport.update({
  id: '/api/places/details',
  path: '/api/places/details',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesAutocompleteRoute = ApiPlacesAutocompleteRouteImport.update({
  id: '/api/places/autocomplete',
  path: '/api/places/autocomplete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-match': typeof AdminMatchRoute
  '/events': typeof EventsRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/municipality': typeof MunicipalityRoute
  '/onboarding': typeof OnboardingRoute
  '/organiser': typeof OrganiserRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/suggested': typeof SuggestedRoute
  '/verify': typeof VerifyRoute
  '/event/$id': typeof EventIdRoute
  '/api/places/autocomplete': typeof ApiPlacesAutocompleteRoute
  '/api/places/details': typeof ApiPlacesDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-match': typeof AdminMatchRoute
  '/events': typeof EventsRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/municipality': typeof MunicipalityRoute
  '/onboarding': typeof OnboardingRoute
  '/organiser': typeof OrganiserRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/suggested': typeof SuggestedRoute
  '/verify': typeof VerifyRoute
  '/event/$id': typeof EventIdRoute
  '/api/places/autocomplete': typeof ApiPlacesAutocompleteRoute
  '/api/places/details': typeof ApiPlacesDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-match': typeof AdminMatchRoute
  '/events': typeof EventsRoute
  '/interests': typeof InterestsRoute
  '/login': typeof LoginRoute
  '/municipality': typeof MunicipalityRoute
  '/onboarding': typeof OnboardingRoute
  '/organiser': typeof OrganiserRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/suggested': typeof SuggestedRoute
  '/verify': typeof VerifyRoute
  '/event/$id': typeof EventIdRoute
  '/api/places/autocomplete': typeof ApiPlacesAutocompleteRoute
  '/api/places/details': typeof ApiPlacesDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-match'
    | '/events'
    | '/interests'
    | '/login'
    | '/municipality'
    | '/onboarding'
    | '/organiser'
    | '/search'
    | '/settings'
    | '/signup'
    | '/suggested'
    | '/verify'
    | '/event/$id'
    | '/api/places/autocomplete'
    | '/api/places/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-match'
    | '/events'
    | '/interests'
    | '/login'
    | '/municipality'
    | '/onboarding'
    | '/organiser'
    | '/search'
    | '/settings'
    | '/signup'
    | '/suggested'
    | '/verify'
    | '/event/$id'
    | '/api/places/autocomplete'
    | '/api/places/details'
  id:
    | '__root__'
    | '/'
    | '/admin-match'
    | '/events'
    | '/interests'
    | '/login'
    | '/municipality'
    | '/onboarding'
    | '/organiser'
    | '/search'
    | '/settings'
    | '/signup'
    | '/suggested'
    | '/verify'
    | '/event/$id'
    | '/api/places/autocomplete'
    | '/api/places/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminMatchRoute: typeof AdminMatchRoute
  EventsRoute: typeof EventsRoute
  InterestsRoute: typeof InterestsRoute
  LoginRoute: typeof LoginRoute
  MunicipalityRoute: typeof MunicipalityRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganiserRoute: typeof OrganiserRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SuggestedRoute: typeof SuggestedRoute
  VerifyRoute: typeof VerifyRoute
  EventIdRoute: typeof EventIdRoute
  ApiPlacesAutocompleteRoute: typeof ApiPlacesAutocompleteRoute
  ApiPlacesDetailsRoute: typeof ApiPlacesDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suggested': {
      id: '/suggested'
      path: '/suggested'
      fullPath: '/suggested'
      preLoaderRoute: typeof SuggestedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organiser': {
      id: '/organiser'
      path: '/organiser'
      fullPath: '/organiser'
      preLoaderRoute: typeof OrganiserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipality': {
      id: '/municipality'
      path: '/municipality'
      fullPath: '/municipality'
      preLoaderRoute: typeof MunicipalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-match': {
      id: '/admin-match'
      path: '/admin-match'
      fullPath: '/admin-match'
      preLoaderRoute: typeof AdminMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places/details': {
      id: '/api/places/details'
      path: '/api/places/details'
      fullPath: '/api/places/details'
      preLoaderRoute: typeof ApiPlacesDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places/autocomplete': {
      id: '/api/places/autocomplete'
      path: '/api/places/autocomplete'
      fullPath: '/api/places/autocomplete'
      preLoaderRoute: typeof ApiPlacesAutocompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminMatchRoute: AdminMatchRoute,
  EventsRoute: EventsRoute,
  InterestsRoute: InterestsRoute,
  LoginRoute: LoginRoute,
  MunicipalityRoute: MunicipalityRoute,
  OnboardingRoute: OnboardingRoute,
  OrganiserRoute: OrganiserRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SuggestedRoute: SuggestedRoute,
  VerifyRoute: VerifyRoute,
  EventIdRoute: EventIdRoute,
  ApiPlacesAutocompleteRoute: ApiPlacesAutocompleteRoute,
  ApiPlacesDetailsRoute: ApiPlacesDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
